### ISSUE TITLE
Creation of Reponse Type Standard

### ISSUE THREAD

**Issue by bulentrahimkazanci** [SWEZenith/Living-History-API#22]
All response coming from API should include a standard format.
String body causes json conversion problem on client side.

**Comment by yaseminalpay** [comment]
How about returning everything in ResponseEntity? would it solve this issue?

**Comment by yaseminalpay** [comment]
How about returning everything in ResponseEntity? would it solve this issue?

**Comment by gokceyucel** [comment]
@bulentrahimkazanci Which specific endpoint returns string body?
