### ISSUE TITLE
Implement tests

### ISSUE THREAD

**Issue by gokceyucel** [SWEZenith/Living-History-API#25]

**Comment by yaseminalpay** [comment]
unit + integration?

**Comment by yaseminalpay** [comment]
unit + integration?

**Comment by gokceyucel** [comment]
Since we don't have many cases to implement unit tests, I think our need is mostly integration tests. I have implemented json-ld serialization and deserialization tests along with repository tests. But our controllers should be tested as well.

**Comment by yaseminalpay** [comment]
ok. assigning this to myself.

**Comment by gokceyucel** [comment]
Here is some repository tests: https://github.com/SWEZenith/Living-History-API/blob/master/src/test/java/com/zenith/livinghistory/api/zenithlivinghistoryapi/data/repository/AnnotationRepositoryTest.java

Here is some serialization-deserialization tests: https://github.com/SWEZenith/Living-History-API/blob/master/src/test/java/com/zenith/livinghistory/api/zenithlivinghistoryapi/dto/AnnotationJson.java

**Comment by pinarersoy** [comment]
49a445b
